version: '3.7'

services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - postgres_network
    deploy:
      resources:
        limits:
          memory: '256M'

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start-dev
    environment:
      #KC_LOG_LEVEL: DEBUG
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - postgres_network
      - keycloak_network
    deploy:
      resources:
        limits:
          memory: '512M'

  redis:
    image: redis:7.2.1
    networks:
      - redis_network
    deploy:
      resources:
        limits:
          memory: '128M'

  gateway:
    image: optimove-gateway:0.0.1
    ports:
      - ${GATEWAY_PORT}:8080
    depends_on:
      - keycloak
      - redis
    networks:
      - keycloak_network
      - services_network
      - redis_network
    environment:
      - OIDC_HOST=${OIDC_HOST}
      - OIDC_REALM=${OIDC_REALM}
      - OIDC_CLIENT=${OIDC_CLIENT}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - DEVICEMANAGEMENT_PORT=${DEVICEMANAGEMENT_PORT}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    deploy:
      resources:
        limits:
          memory: '512M'

  devicemanagement:
    image: optimove-devicemanagement:0.0.1
    depends_on:
      - gateway
    networks:
      - services_network
    environment:
      - OIDC_HOST=${OIDC_HOST}
      - OIDC_REALM=${OIDC_REALM}
      - DEVICEMANAGEMENT_PORT=${DEVICEMANAGEMENT_PORT}
    deploy:
      resources:
        limits:
          memory: '256M'

volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge

  services_network:
    driver: bridge

  postgres_network:
    driver: bridge

  redis_network:
    driver: bridge