version: '3.7'

services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start-dev
    environment:
      #KC_LOG_LEVEL: DEBUG
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: admin123
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network

  gateway:
    image: spring-cloud-gateway:latest
    ports:
      - 8081:8080
    depends_on:
      - keycloak
    networks:
      - keycloak_network
    environment:
      - OIDC_HOST=192.168.56.116:8080
      - OIDC_REALM=myrealm
      - OIDC_CLIENT=secure-app
      - OIDC_CLIENT_SECRET=ish9gesPro0VkbUYXjuKfc4y801HPIeH

volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge