apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-internal
  namespace: ingress-nginx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
