apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-application-config
data:
  application.yml: |
    server:
      port: 8080

    spring:
      data:
        redis:
          host: ${SPRING_REDIS_HOST:redis}
          port: ${SPRING_REDIS_PORT:6379}

      application:
        name: gateway

      security:
        oauth2:
          client:
            registration:
              keycloak:
                client-id: ${OIDC_CLIENT}
                client-secret: ${OIDC_CLIENT_SECRET}
                scope: openid, profile
                authorization-grant-type: authorization_code
                redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider:
              keycloak:
                authorization-uri: http://${OIDC_HOST}/realms/${OIDC_REALM}/protocol/openid-connect/auth
                token-uri: http://${OIDC_HOST}/realms/${OIDC_REALM}/protocol/openid-connect/token
                user-info-uri: http://${OIDC_HOST}/realms/${OIDC_REALM}/protocol/openid-connect/userinfo
                jwk-set-uri: http://${OIDC_HOST}/realms/${OIDC_REALM}/protocol/openid-connect/certs
                user-name-attribute: preferred_username
          resource-server:
            jwt:
              jwk-set-uri: http://${OIDC_HOST}/realms/${OIDC_REALM}/protocol/openid-connect/certs

      cloud:
        gateway:
          default-filters:
            - TokenRelay
          routes:
            - id: devicemanagement
              uri: http://devicemanagement:${DEVICEMANAGEMENT_PORT}
              predicates:
                - Path=/devicemanagement/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 2
                    redis-rate-limiter.burstCapacity: 2
                    key-resolver: '#{@ipKeyResolver}'