apiVersion: v1
kind: Service
metadata:
  name: devicemanagement
  namespace: backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: devicemanagement
    version: green
  type: ClusterIP
