apiVersion: apps/v1
kind: Deployment
metadata:
  name: devicemanagement-green
  namespace: backend
  labels:
    app: devicemanagement
    version: green
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: devicemanagement
      version: green
  template:
    metadata:
      labels:
        app: devicemanagement
        version: green
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      containers:
      - name: devicemanagement
        image: optimove-devicemanagement:0.0.9
        env:
        - name: OIDC_HOST
          valueFrom:
            configMapKeyRef:
              name: devicemanagement-config
              key: OIDC_HOST
        - name: OIDC_REALM
          valueFrom:
            configMapKeyRef:
              name: devicemanagement-config
              key: OIDC_REALM
        - name: DEVICEMANAGEMENT_PORT
          valueFrom:
            configMapKeyRef:
              name: devicemanagement-config
              key: DEVICEMANAGEMENT_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: devicemanagement-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: devicemanagement-config
              key: POSTGRES_USER
        - name: POSTGRES_URL
          valueFrom:
            configMapKeyRef:
              name: devicemanagement-config
              key: POSTGRES_URL
        - name: TIMESERIES_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: devicemanagement-config
              key: TIMESERIES_SERVICE_URL
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: devicemanagement-secret
              key: POSTGRES_PASSWORD
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            memory: "512Mi"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config/application.yml
          subPath: application.yml
        ports:
        - containerPort: 8080
      volumes:
      - name: config-volume
        configMap:
          name: devicemanagement-application-config
      initContainers:
      - name: wait-for-gateway
        image: busybox
        command: ['sh', '-c', 'until nc -z gateway.default.svc.cluster.local 8080; do echo waiting for gateway; sleep 2; done;']
