apiVersion: v1
kind: ConfigMap
metadata:
  name: timeseries-application-config
  namespace: backend
data:
  application.yml: |
    spring:
      application:
        name: timeseries
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: http://${OIDC_HOST}/realms/${OIDC_REALM}/protocol/openid-connect/certs
    influxdb:
      url: "http://${INFLUXDB_HOSTNAME}:8086"
      token: ""
      org: ${INFLUXDB_ORG}
      bucket: ${INFLUXDB_BUCKET}
      username: ${INFLUXDB_USER}
      password: ${INFLUXDB_PASSWORD}
    server:
      port: ${TIMESERIES_PORT}
