apiVersion: v1
kind: ConfigMap
metadata:
  name: timeseries-config
  namespace: backend
data:
  OIDC_HOST: "keycloak.default.svc.cluster.local:8080"
  OIDC_REALM: "optimove"
  TIMESERIES_PORT: "8080"
  INFLUXDB_USER: "optimoveuser"
  INFLUXDB_HOSTNAME: "influxdb.default.svc.cluster.local"
  INFLUXDB_ORG: "optimove_org"
  INFLUXDB_BUCKET: "optimove_bucket"